=== alex-dot/flock-protocol/flock_fsm.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
targetNamespace="flock-protocol"
xmlns="flock-protocol"
elementFormDefault="qualified">

<xs:element name="class" type="class_el"/>

<xs:complexType name="class_el">
  <xs:sequence>
    <xs:element name="state" minOccurs="1" maxOccurs="unbounded" type="state_el"/>
  </xs:sequence>
  <xs:attribute name="name" type="xs:string"/>
</xs:complexType>

<xs:complexType name="state_el">
  <xs:sequence>
    <xs:element name="event" minOccurs="1" maxOccurs="unbounded" type="event_el"/>
  </xs:sequence>
  <xs:attribute name="name" type="xs:string"/>
  <xs:attribute name="inherit" type="xs:string"/>
  <xs:attribute name="start" type="xs:string"/>
  <xs:attribute name="current_status" type="xs:string"/>
</xs:complexType>

<xs:complexType name="event_el">
  <xs:sequence>
    <xs:element name="action" minOccurs="1" maxOccurs="1" type="action_el"/>
  </xs:sequence>
  <xs:attribute name="name" type="xs:string"/>
  <xs:attribute name="next" type="xs:string"/>
  <xs:attribute name="received_status" type="xs:string"/>
  <xs:attribute name="internal" type="xs:string"/>
  <xs:attribute name="emergency" type="xs:string"/>
</xs:complexType>

<xs:complexType name="action_el">
  <xs:attribute name="name" type="xs:string"/>
  <xs:attribute name="next_status" type="xs:string"/>
</xs:complexType>

</xs:schema>

=== alex-dot/flock-protocol/flock_fsm.xml
<class name = "flock_fsm" version="1.0.0"
xmlns="flock-protocol" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="flock-protocol flock_fsm.xsd">

<state name = "ready" inherit = "exit" start = "true" current_status = "100" >
    <event name = "new local file" next = "announcing new file" received_status = "300" >
        <action name = "send heartbeat" next_status = "120" />
    </event>
    <event name = "new local file with more" next = "announcing new file with more" received_status = "304" >
        <action name = "send heartbeat" next_status = "124" />
    </event>
    <event name = "local file metadata change" next = "announcing file metadata change" received_status = "320" >
        <action name = "send heartbeat" next_status = "160" />
    </event>
    <event name = "local file metadata change with more" next = "announcing file metadata change with more" received_status = "324" >
        <action name = "send heartbeat" next_status = "164" />
    </event>
    <event name = "received heartbeat" next = "ready" received_status = "100" >
        <action name = "send heartbeat" next_status = "100" />
    </event>
    <event name = "received heartbeat" next = "acknowledging new file" received_status = "120" >
        <action name = "send heartbeat" next_status = "121" />
    </event>
    <event name = "received heartbeat" next = "acknowledging new file with more" received_status = "124" >
        <action name = "send heartbeat" next_status = "125" />
    </event>
    <event name = "received heartbeat" next = "acknowledging file metadata change" received_status = "160" >
        <action name = "send heartbeat" next_status = "161" />
    </event>
    <event name = "received heartbeat" next = "acknowledging file metadata change with more" received_status = "164" >
        <action name = "send heartbeat" next_status = "165" />
    </event>
    <event name = "received heartbeat" next = "ready" received_status = "150" >
        <action name = "send heartbeat" next_status = "100" />
    </event>
</state>

<state name = "announcing new file" inherit = "exit" current_status = "120" >
    <event name = "received heartbeat" next = "announcing new file" received_status = "121" >
        <action name = "send heartbeat" next_status = "120" />
    </event>
    <event name = "all nodes replied" next = "sending new file metadata" received_status = "122" internal = "true" >
        <action name = "send heartbeat" next_status = "130" />
    </event>

    <event name = "new local file" next = "announcing new file with more" received_status = "300" >
        <action name = "send heartbeat" next_status = "124" />
    </event>
    <event name = "new local file reported twice" next = "announcing new file" received_status = "301" >
        <action name = "send heartbeat" next_status = "120" />
    </event>
    <event name = "new local file with more" next = "announcing new file with more" received_status = "304" >
        <action name = "send heartbeat" next_status = "124" />
    </event>
    <event name = "local file metadata change" next = "announcing file metadata change with more" received_status = "320" >
        <action name = "send heartbeat" next_status = "164" />
    </event>
    <event name = "local file metadata change with more" next = "announcing file metadata change with more" received_status = "324" >
        <action name = "send heartbeat" next_status = "164" />
    </event>
</state>

<state name = "announcing new file with more" inherit = "exit" current_status = "124" >
    <event name = "received heartbeat" next = "announcing new file with more" received_status = "125" >
        <action name = "send heartbeat" next_status = "124" />
    </event>
    <event name = "all nodes replied" next = "sending new file metadata with more" received_status = "126" >
        <action name = "send heartbeat" next_status = "134" />
    </event>

    <event name = "new local file" next = "announcing new file with more" received_status = "300" >
        <action name = "send heartbeat" next_status = "124" />
    </event>
    <event name = "new local file with more" next = "announcing new file with more" received_status = "304" >
        <action name = "send heartbeat" next_status = "124" />
    </event>
    <event name = "local file metadata change" next = "announcing file metadata change with more" received_status = "320" >
        <action name = "send heartbeat" next_status = "164" />
    </event>
    <event name = "local file metadata change with more" next = "announcing file metadata change with more" received_status = "324" >
        <action name = "send heartbeat" next_status = "164" />
    </event>
</state>

<state name = "announcing file metadata change" inherit = "exit" current_status = "160" >
    <event name = "received heartbeat" next = "announcing file metadata change" received_status = "161" >
        <action name = "send heartbeat" next_status = "160" />
    </event>
    <event name = "all nodes replied" next = "sending file metadata change" received_status = "162" internal = "true" >
        <action name = "send heartbeat" next_status = "170" />
    </event>

    <event name = "new local file" next = "announcing file metadata change with more" received_status = "300" >
        <action name = "send heartbeat" next_status = "164" />
    </event>
    <event name = "new local file with more" next = "announcing file metadata change with more" received_status = "304" >
        <action name = "send heartbeat" next_status = "164" />
    </event>
    <event name = "local file metadata change" next = "announcing file metadata change with more" received_status = "320" >
        <action name = "send heartbeat" next_status = "164" />
    </event>
    <event name = "local file metadata change with more" next = "announcing file metadata change with more" received_status = "324" >
        <action name = "send heartbeat" next_status = "164" />
    </event>
</state>

<state name = "announcing file metadata change with more" inherit = "exit" current_status = "164" >
    <event name = "received heartbeat" next = "announcing file metadata change with more" received_status = "165" >
        <action name = "send heartbeat" next_status = "164" />
    </event>
    <event name = "all nodes replied" next = "sending file metadata change with more" received_status = "166" internal = "true" >
        <action name = "send heartbeat" next_status = "174" />
    </event>

    <event name = "new local file" next = "announcing file metadata change with more" received_status = "300" >
        <action name = "send heartbeat" next_status = "164" />
    </event>
    <event name = "new local file with more" next = "announcing file metadata change with more" received_status = "304" >
        <action name = "send heartbeat" next_status = "164" />
    </event>
    <event name = "local file metadata change" next = "announcing file metadata change with more" received_status = "320" >
        <action name = "send heartbeat" next_status = "164" />
    </event>
    <event name = "local file metadata change with more" next = "announcing file metadata change with more" received_status = "324" >
        <action name = "send heartbeat" next_status = "164" />
    </event>
</state>

<state name = "sending new file metadata" inherit = "exit" current_status = "130" >
    <event name = "received heartbeat" next = "sending new file metadata" received_status = "131" >
        <action name = "send heartbeat" next_status = "130" />
    </event>
    <event name = "timing offset elapsed" next = "sending new file" received_status = "132" internal = "true" >
        <action name = "send heartbeat" next_status = "110" />
    </event>

    <event name = "new local file" next = "sending new file metadata" received_status = "300" >
        <action name = "add new file to queue" next_status = "130" />
    </event>
    <event name = "new local file with more" next = "sending new file metadata" received_status = "304" >
        <action name = "add new file to queue" next_status = "130" />
    </event>
    <event name = "local file metadata change" next = "sending new file metadata" received_status = "320" >
        <action name = "add new file to queue" next_status = "130" />
    </event>
    <event name = "local file metadata change with more" next = "sending new file metadata" received_status = "324" >
        <action name = "add new file to queue" next_status = "130" />
    </event>
</state>

<state name = "sending new file metadata with more" inherit = "exit" current_status = "134" >
    <event name = "received heartbeat" next = "sending new file metadata with more" received_status = "135" >
        <action name = "send heartbeat" next_status = "134" />
    </event>
    <event name = "timing offset elapsed" next = "sending new file with more alpha" received_status = "132" internal = "true" >
        <action name = "send heartbeat" next_status = "114" />
    </event>

    <event name = "new local file" next = "sending new file metadata with more" received_status = "300" >
        <action name = "send heartbeat" next_status = "134" />
    </event>
    <event name = "new local file with more" next = "sending new file metadata with more" received_status = "304" >
        <action name = "send heartbeat" next_status = "134" />
    </event>
    <event name = "local file metadata change" next = "sending new file metadata with more" received_status = "320" >
        <action name = "add new file to queue" next_status = "134" />
    </event>
    <event name = "local file metadata change with more" next = "sending new file metadata with more" received_status = "324" >
        <action name = "add new file to queue" next_status = "134" />
    </event>
</state>

<state name = "sending file metadata change" inherit = "exit" current_status = "170" >
    <event name = "received heartbeat" next = "sending file metadata change" received_status = "171" >
